# Generated by Django 2.2.6 on 2019-11-27 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_disease', message='Όνομα πάθησης', regex='^[\\w\\-,\\(\\) ]*$')])),
                ('code', models.CharField(blank=True, default='', max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_disease', message='Κωδικοποίηση πάθησης', regex='^\\d{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_drug', message='Όνομα φαρμάκου', regex='^[\\w\\-,\\(\\) ]*$')])),
                ('code', models.CharField(blank=True, default='', max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_drug', message='Κωδικοποίηση φαρμάκου', regex='^[a-zA-Z]{1}[0-9]{2}[a-zA-Z]{2}[0-9]{2}$')])),
                ('synonyms', models.ManyToManyField(blank=True, default=None, related_name='_drug_synonyms_+', to='app.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATING', 'Υπό δημιουργία'), ('RUNNING', 'Τρέχει'), ('COMPLETED', 'Ολοκληρώθηκε')], default='CREATING', max_length=9, unique=True, verbose_name='Κατάσταση: ')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Τίτλος Σεναρίου', regex='^[\\w\\-,\\(\\) ]*$')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(default=None, related_name='condition_scenarios', to='app.Condition', verbose_name='conditions')),
                ('drugs', models.ManyToManyField(default=None, related_name='drug_scenarios', to='app.Drug', verbose_name='drugs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Status')),
            ],
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_condition'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='unique_scenario'),
        ),
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_drug'),
        ),
    ]
