# Generated by Django 2.2.6 on 2021-08-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseToQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaseToScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(default=None, null=True)),
                ('q2', models.BooleanField(default=None, null=True)),
                ('q3', models.BooleanField(default=None, null=True)),
                ('q4', models.BooleanField(default=None, null=True)),
                ('q5', models.BooleanField(default=None, null=True)),
                ('q6', models.BooleanField(default=None, null=True)),
                ('q7', models.BooleanField(default=None, null=True)),
                ('q8', models.BooleanField(default=None, null=True)),
                ('q9', models.BooleanField(default=None, null=True)),
                ('q10', models.BooleanField(default=None, null=True)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patientcase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='patientcase',
            constraint=models.UniqueConstraint(fields=('patient_id', 'timestamp'), name='unique_patientcase'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'), name='unique_patientcase'),
        ),
        migrations.AddField(
            model_name='casetoscenario',
            name='pcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PatientCase'),
        ),
        migrations.AddField(
            model_name='casetoscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
        migrations.AddField(
            model_name='casetoquestionnaire',
            name='pcaseq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PatientCase'),
        ),
        migrations.AddField(
            model_name='casetoquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Questionnaire'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='questionnaires',
            field=models.ManyToManyField(default=None, related_name='questionnaires', through='app.CaseToQuestionnaire', to='app.Questionnaire', verbose_name='questionnaires'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='scenarios',
            field=models.ManyToManyField(default=None, related_name='scenarios', through='app.CaseToScenario', to='app.Scenario', verbose_name='scenarios'),
        ),
        migrations.AddConstraint(
            model_name='casetoscenario',
            constraint=models.UniqueConstraint(fields=('scenario', 'pcase'), name='unique_casetogether'),
        ),
        migrations.AddConstraint(
            model_name='casetoquestionnaire',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'pcaseq'), name='unique_casetogetherq'),
        ),
    ]
