# Generated by Django 2.2.6 on 2021-04-21 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseToScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scenarios', models.ManyToManyField(default=None, related_name='scenarios', through='app.CaseToScenario', to='app.Scenario', verbose_name='scenarios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='casetoscenario',
            name='pcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PatientCase'),
        ),
        migrations.AddField(
            model_name='casetoscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
        migrations.AddConstraint(
            model_name='patientcase',
            constraint=models.UniqueConstraint(fields=('patient', 'timestamp'), name='unique_patientcase'),
        ),
        migrations.AddConstraint(
            model_name='casetoscenario',
            constraint=models.UniqueConstraint(fields=('scenario', 'pcase'), name='unique_casetogether'),
        ),
    ]
