# Generated by Django 2.2.6 on 2019-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='conditions',
            field=models.ManyToManyField(default=None, related_name='conditions', to='app.Condition', verbose_name='conditions'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='drugs',
            field=models.ManyToManyField(default=None, related_name='drugs', to='app.Drug', verbose_name='drugs'),
        ),
    ]
