# Generated by Django 3.2.8 on 2022-03-21 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_pubmed_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientCase',
            new_name='IndividualCase',
        ),
        migrations.RemoveConstraint(
            model_name='individualcase',
            name='unique_patientcase',
        ),
        migrations.RenameField(
            model_name='individualcase',
            old_name='patient_id',
            new_name='indiv_case_id',
        ),
        migrations.AddConstraint(
            model_name='individualcase',
            constraint=models.UniqueConstraint(fields=('indiv_case_id', 'timestamp'), name='unique_individualcase'),
        ),
    ]
