# Generated by Django 2.2.6 on 2021-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210421_1654'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientcase',
            name='unique_patientcase',
        ),
        migrations.RenameField(
            model_name='patientcase',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AddConstraint(
            model_name='patientcase',
            constraint=models.UniqueConstraint(fields=('patient_id', 'timestamp'), name='unique_patientcase'),
        ),
    ]
