# Generated by Django 3.2.11 on 2022-01-24 15:18

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_pubmed_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseToQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaseToScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator('\\d{4}[A-Z]{3}\\d{7}', 'Παράδειγμα ορθού αναγνωριστικού: 0001PGH0000001')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(default=None, null=True)),
                ('q2', models.BooleanField(default=None, null=True)),
                ('q3', models.BooleanField(default=None, null=True)),
                ('q4', models.BooleanField(default=None, null=True)),
                ('q5', models.BooleanField(default=None, null=True)),
                ('q6', models.BooleanField(default=None, null=True)),
                ('q7', models.BooleanField(default=None, null=True)),
                ('q8', models.BooleanField(default=None, null=True)),
                ('q9', models.BooleanField(default=None, null=True)),
                ('q10', models.BooleanField(default=None, null=True)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='wsview',
            field=models.TextField(default=''),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'), name='unique_questionnaire'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='questionnaires',
            field=models.ManyToManyField(default=None, related_name='questionnaires', through='app.CaseToQuestionnaire', to='app.Questionnaire', verbose_name='questionnaires'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='scenarios',
            field=models.ManyToManyField(default=None, related_name='scenarios', through='app.CaseToScenario', to='app.Scenario', verbose_name='scenarios'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetoscenario',
            name='pcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patientcase'),
        ),
        migrations.AddField(
            model_name='casetoscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenario'),
        ),
        migrations.AddField(
            model_name='casetoquestionnaire',
            name='pcaseq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patientcase'),
        ),
        migrations.AddField(
            model_name='casetoquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionnaire'),
        ),
        migrations.AddConstraint(
            model_name='patientcase',
            constraint=models.UniqueConstraint(fields=('patient_id', 'timestamp'), name='unique_patientcase'),
        ),
        migrations.AddConstraint(
            model_name='casetoscenario',
            constraint=models.UniqueConstraint(fields=('scenario', 'pcase'), name='unique_pcase_scenario'),
        ),
        migrations.AddConstraint(
            model_name='casetoquestionnaire',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'pcaseq'), name='unique_questionnaire_pcaseq'),
        ),
    ]
