# Generated by Django 2.2.6 on 2020-11-24 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201124_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='workspace',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
