# Generated by Django 2.2.6 on 2019-12-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191212_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Status'),
        ),
    ]
