# Generated by Django 3.1.7 on 2021-03-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notes_note_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notes',
            name='unique_condition',
        ),
        migrations.AddConstraint(
            model_name='notes',
            constraint=models.UniqueConstraint(fields=('user', 'scenario', 'workspace', 'wsview'), name='unique_note'),
        ),
    ]
