# Generated by Django 2.2.6 on 2021-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210421_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField()),
                ('q2', models.BooleanField()),
                ('q3', models.BooleanField()),
                ('q4', models.BooleanField()),
                ('q5', models.BooleanField()),
                ('q6', models.BooleanField()),
                ('q7', models.BooleanField()),
                ('q8', models.BooleanField()),
                ('q9', models.BooleanField()),
                ('q10', models.BooleanField()),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'), name='unique_patientcase'),
        ),
    ]
