# Generated by Django 2.2.6 on 2021-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210506_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='q1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q10',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q2',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q3',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q4',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q5',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q6',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q7',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q8',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='q9',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
