# Generated by Django 2.2.6 on 2020-09-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191217_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('CREATING', 'Υπό δημιουργία'), ('RUNNING', 'Σε εξέλιξη'), ('COMPLETED', 'Ολοκληρώθηκε')], default='CREATING', max_length=9, unique=True, verbose_name='Κατάσταση: '),
        ),
        migrations.CreateModel(
            name='OHDSIWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir_id', models.IntegerField(blank=True, null=True)),
                ('ch_id', models.IntegerField(blank=True, null=True)),
                ('cp_id', models.IntegerField(blank=True, null=True)),
                ('sc_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Status')),
            ],
        ),
    ]
