# Generated by Django 2.2.6 on 2021-05-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210511_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseToQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcaseq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PatientCase')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='patientcase',
            name='questionnaires',
            field=models.ManyToManyField(default=None, related_name='questionnaires', through='app.CaseToQuestionnaire', to='app.Questionnaire', verbose_name='questionnaires'),
        ),
        migrations.AddConstraint(
            model_name='casetoquestionnaire',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'pcaseq'), name='unique_casetogetherq'),
        ),
    ]
