# Generated by Django 2.2.6 on 2020-10-14 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20200921_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohdsiworkspace',
            name='ch_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='ohdsiworkspace',
            name='cp_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='ohdsiworkspace',
            name='ir_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.CreateModel(
            name='PubMed',
            fields=[
                ('pid', models.CharField(default='', max_length=70, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('pubdate', models.CharField(default='', max_length=400)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('authors', models.CharField(default='', max_length=400)),
                ('url', models.CharField(default='', max_length=100)),
                ('relevance', models.CharField(choices=[(True, 'Relevant'), (False, 'Irrelevant'), ('Not sure', 'Not sure')], default='', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
