"""
Django settings for gentelella project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '<APP_SECRET_KEY>'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'app',
    'users',
    'crispy_forms',
    'ckeditor',
    'ckeditor_uploader',
    'dynamic_breadcrumbs',
    # 'corsheaders',
    'django_select2',
    'django_translation_flags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PasswordChangeMiddleware',
]

# CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'gentelella.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'dynamic_breadcrumbs.context_processors.breadcrumbs',
            ],
        },
    },
]

WSGI_APPLICATION = 'gentelella.wsgi.application'

SOCIAL_AUTH_MENDELEY_OAUTH2_KEY = '<PVCLINICAL_MENDELEY_OAUTH2_KEY>'
SOCIAL_AUTH_MENDELEY_OAUTH2_SECRET = '<PVCLINICAL_MENDELEY_OAUTH2_SECRET>'

PUBMED_EMAIL = '<PVCLINICAL_PROJECT_EMAIL_ACCOUNT>'
PUBMED_KEY = '<PVCLINICAL_PUBMED_KEY>'

ENTREZ_EMAIL = '<PVCLINICAL_PROJECT_EMAIL_ACCOUNT>'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.mendeley.MendeleyOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': '<DB_ENGINE> e.g. django.db.backends.postgresql',
        'NAME': '<DB_NAME>',
        'USER': '<DB_USERNAME>',
        'PASSWORD': '<DB_USER_PASSWORD>',
        'HOST': '<DB_HOST_ADDRESS>',
        'PORT': '<DB_HOST_PORT_NUMBER>',
        'OPTIONS': {
            'sql_mode': 'traditional',
        },

    }
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'app.password_validators.ComplexPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'el-GR'
# LANGUAGE_CODE = 'en-US'
LANGUAGES = (
    ('el', _('Ελληνικά')),
    ('en', _('Αγγλικά')),
)

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = (
    '%d.%m.%Y', '%d.%m.%Y', '%d.%m.%y',  # '25.10.2006', '25.10.2006', '25.10.06'
    '%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y',  # '25-10-2006', '25/10/2006', '25/10/06'
    '%d %b %Y',  # '25 Oct 2006',
    '%d %B %Y',  # '25 October 2006',
)

DATE_FORMAT = '%d.%m.%Y'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
                )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800
SESSION_SAVE_EVERY_REQUEST = True
# IMPORT_EXPORT_USE_TRANSACTIONS = False
DEFAULT_FROM_EMAIL = 'PROJECT MAILER <email@example.com>'
SERVER_EMAIL = 'email@example.com'
EMAIL_USE_TLS = True
EMAIL_HOST = '<YOUR_EMAIL_HOST>'
EMAIL_HOST_USER = '<YOUR_EMAIL_HOST_USER>'
EMAIL_HOST_PASSWORD = '<YOUR_EMAIL_HOST_PASSWORD>'
EMAIL_PORT = 587


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SPARQL_ENDPOINT = "<SPARQL_ENDPOINT>"
SPARQL_PREFIXES = {
    # "dc": "http://purl.org/dc/elements/1.1/"
}
SPARQL_USERNAME = "<SPARQL_USER>"
SPARQL_PASSWORD = "<SPARQL_PASSWORD>"
SPARQL_DRUGS_URI = "<DRUGBANK_GRAPH_URI>"
SPARQL_ATCS_URI = "<BIOONTOLOGY_UATC_GRAPH_URI>"
SPARQL_MEDDRA_URI = "<MEDDRA_GRAPH_URI>"
SPARQL_REALM = "SPARQL Endpoint"  # Default value is SPARQL
SPARQL_AUTH = "DIGEST"  # Default value is BASIC


CACHES = {
    'default': {
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # ''django.core.cache.backends.memcached.MemcachedCache',
        # 'LOCATION': 'MedDataCache',  # '127.0.0.1:11211',
        # 'TIMEOUT': None,
        # 'OPTIONS': {
        #     'MAX_ENTRIES': 500000,
        # }
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            # "PASSWORD": "PASSWORD_IF_ANY",
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "<KEY_PREFIX>"
    }
}

JSONS_DIR = os.path.join(BASE_DIR, "jsons")

OHDSI_ENDPOINT = "<OHDSI_SERVER>/WebAPI"
OHDSI_ATLAS = "<OHDSI_SERVER>/atlas"
OHDSI_CDM_NAME = "<OHDSI-CDM_NAME>"

OPENFDA_SHINY_ENDPOINT = "<OPENFDA_SHINY_APPS_ENDPOINT>"

SM_SHINY_ENDPOINT = "<SOCIAL_MEDIA_SHINY_APPS_ENDPOINT>"
TWITTER_CREDENTIALS = {"twitterAccessToken": "<TWITTER_ACCESS_TOKEN>",
                       "twitterAccessTokenSecret": "<TWITTER_ACCESS_TOKEN_SECRET>",
                       "twitterConsumerKey": "<TWITTER_CONSUMER_KEY>",
                       "twitterConsumerSecret": "<TWITTER_CONSUMER_SECRET>"}

WORKSPACES = {"OHDSI": 1, "OpenFDA": 2, "PubMed": 3, "SocialMedia": 4}
ABBRV_VIEWS = {"de": _("Έκθεση σε Φάρμακα"), "co": _("Εκδήλωση Κατάστασης"), "ir": _("Ρυθμός Επίπτωσης"),
               "char": _("Χαρακτηρισμός Πληθυσμού"), "cp": _("Μονοπάτι Ακολουθίας Συμβάντων"), "sm": _("Μέσα Κοινωνικής Δικτύωσης")}

# If cohort was generated before this days limit, it should be regenerated
COHORT_RECENT_DAYS_LIMIT = 90

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 291,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat'],
        ],
        'removePlugins': 'elementspath',
    }
}

SELECT2_CSS = "vendors/select2/dist/css/select2.min.css"
SELECT2_JS = "vendors/select2/dist/js/select2.full.min.js"
SELECT2_I18N_PATH = "vendors/select2/dist/js/i18n/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

REPORT_ENDPOINT = "<REPORT_ENDPOINT>"
SHINY_SCREENSHOTS_ENDPOINT = "<SHINY_SCREENSHOTS_ENDPOINT>"

SHINY_SHOTS_SERVICES_USER = "<OPENFDA_SHOTS_SERVICES_USER>"
SHINY_SHOTS_SERVICES_PASS = "<OPENFDA_SHOTS_SERVICES_PASSWORD>"
PDFKIT_ENDPOINT = "http://127.0.0.1:8000"

DYNAMIC_BREADCRUMBS_HOME_LABEL = "index"
X_FRAME_OPTIONS = 'ALLOW-FROM localhost'

X_FRAME_OPTIONS = 'SAMEORIGIN'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
