"""
Django settings for gentelella project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8*md2t)o**67@*yhc(d=f@j95kl(dnf^rmm4s00$-mh_vurb2b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'app',
    'users',
    'crispy_forms',
    'ckeditor',
    'ckeditor_uploader',
    'dynamic_breadcrumbs',
    # 'corsheaders',
    'django_select2',
    'django_translation_flags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PasswordChangeMiddleware',
]

# CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'gentelella.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'dynamic_breadcrumbs.context_processors.breadcrumbs',
            ],
        },
    },
]

WSGI_APPLICATION = 'gentelella.wsgi.application'

SOCIAL_AUTH_MENDELEY_OAUTH2_KEY = '10925'
SOCIAL_AUTH_MENDELEY_OAUTH2_SECRET = 'bchL2wMQjyOf8rml'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.mendeley.MendeleyOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pvdash',
        'USER': 'pvuser',
        'PASSWORD': 'ANKY#V5eGwPH',
        'HOST': '160.40.71.111',
        'PORT': '5432',
        # 'OPTIONS': {
        #     'sql_mode': 'traditional',
        # },
    }
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'app.password_validators.ComplexPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'el-GR'
# LANGUAGE_CODE = 'en-US'
LANGUAGES = (
    ('el', _('Ελληνικά')),
    ('en', _('Αγγλικά')),
)

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_INPUT_FORMATS = (
    '%d.%m.%Y', '%d.%m.%Y', '%d.%m.%y',  # '25.10.2006', '25.10.2006', '25.10.06'
    '%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y',  # '25-10-2006', '25/10/2006', '25/10/06'
    '%d %b %Y',  # '25 Oct 2006',
    '%d %B %Y',  # '25 October 2006',
)

DATE_FORMAT = '%d.%m.%Y'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
                )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800
SESSION_SAVE_EVERY_REQUEST = True
# IMPORT_EXPORT_USE_TRANSACTIONS = False
DEFAULT_FROM_EMAIL = 'PVClinical Mailer <pvclinical@certh.gr>'
SERVER_EMAIL = 'pvclinical@certh.gr'
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.certh.gr'
EMAIL_HOST_USER = 'pvclinical@certh.gr'
EMAIL_HOST_PASSWORD = 'sartuj872459'
EMAIL_PORT = 587


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# SPARQL config
SPARQL_ENDPOINT = "http://160.40.71.111:8890/sparql"
SPARQL_PREFIXES = {
    # "dc": "http://purl.org/dc/elements/1.1/"
}
SPARQL_USERNAME = "pvclinical_user"
SPARQL_PASSWORD = "Y#trm8Q8rQ"
SPARQL_DRUGS_URI = "https://bio2rdf.org/drugbank-patched"
# SPARQL_ATCS_URI = "http://purl.bioontology.org/ontology/UATC/"
SPARQL_MEDDRA_URI = "http://english211.meddra.org"
SPARQL_REALM = "SPARQL Endpoint"  # Default value is SPARQL
SPARQL_AUTH = "DIGEST"  # Default value is BASIC


CACHES = {
    'default': {
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # ''django.core.cache.backends.memcached.MemcachedCache',
        # 'LOCATION': 'MedDataCache',  # '127.0.0.1:11211',
        # 'TIMEOUT': None,
        # 'OPTIONS': {
        #     'MAX_ENTRIES': 500000,
        # }
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "PASSWORD": "KgpMq!t26U",
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "pvclinical"
    }
}

JSONS_DIR = os.path.join(BASE_DIR, "jsons")

OHDSI_ENDPOINT = "https://srv-71-127.inab.certh.gr/WebAPI"
OHDSI_ATLAS = "https://srv-71-127.inab.certh.gr/atlas"
OHDSI_CDM_NAME = "OHDSI-CDMV5-synpuf"

OPENFDA_SHINY_ENDPOINT = "https://srv-71-127.inab.certh.gr/deployshiny/"

SM_SHINY_ENDPOINT = "https://srv-71-127.inab.certh.gr/pv_twitter_analytics/"
# TETHYS_ENDPOINT = "https://pvclinical.inab.certh.gr:8090/tethys/rest/processes/"
TWITTER_CREDENTIALS = {"twitterAccessToken": "573070470-RzByLXTWDohFKTRrlPcjSeYbz0uPdjyGy9KdE1e5",
                       "twitterAccessTokenSecret": "8I10vaLA4jHemdLVWJaMqS2TyXF9pX3cdfq1ei87ncDZj",
                       "twitterConsumerKey": "jWipyb1a5hwZLIKwXLekiet2t",
                       "twitterConsumerSecret": "FchHUmvUnude9W4ItNRUOiMMcto8uTaCrELVF7yc1uVQk9VTTT"}

WORKSPACES = {"OHDSI": 1, "OpenFDA": 2, "PubMed": 3, "SocialMedia": 4}
ABBRV_VIEWS = {"de": _("Έκθεση σε Φάρμακα"), "co": _("Εκδήλωση Κατάστασης"), "ir": _("Ρυθμός Επίπτωσης"),
               "char": _("Χαρακτηρισμός Πληθυσμού"), "cp": _("Μονοπάτι Ακολουθίας Συμβάντων"), "sm": _("Μέσα Κοινωνικής Δικτύωσης")}

# If cohort was generated before this days limit, it should be regenerated
COHORT_RECENT_DAYS_LIMIT = 90

# TINYMCE_DEFAULT_CONFIG = {
#     "mode": "textareas",
#     "theme": "silver",
#     "plugins": "directionality,paste,searchreplace",
#     "directionality": "ltr",
#     "toolbar": 'formatselect | bold italic underline | alignleft aligncenter alignright alignjustify '
#                '| bullist numlist | outdent indent | table | link image | codesample | preview code',
#     "height": 400,  # texteditor height
#
# }

CKEDITOR_UPLOAD_PATH = "uploads/"
# MEDIA_ROOT = "media/"
# MEDIA_URL = "media/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 291,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat'],
        ],
        'removePlugins': 'elementspath',
    }
}

SELECT2_CSS = "vendors/select2/dist/css/select2.min.css"
SELECT2_JS = "vendors/select2/dist/js/select2.full.min.js"
SELECT2_I18N_PATH = "vendors/select2/dist/js/i18n/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

# REPORT_ENDPOINT = "https://srv-71-127.inab.certh.gr/openfda/media/"
#OPENFDA_SCREENSHOTS_ENDPOINT = "https://srv-71-127.inab.certh.gr/media/"

#OPENFDA_SHOTS_SERVICES_USER = "pv_user"
#OPENFDA_SHOTS_SERVICES_PASS = "fNS6@EA5HD"
#PDFKIT_ENDPOINT = "http://127.0.0.1:8000"
DYNAMIC_BREADCRUMBS_HOME_LABEL = "index"
X_FRAME_OPTIONS = 'ALLOW-FROM localhost'
